name: 'Build UI'
description: 'Builds the UI artifact for a SIS cloud app'
inputs:

  workdir:
    description: 'The directory to work from. Can be relative or absolute'
    default: '.'

  artifact:
    description: 'The name of the artifact'
    required: true

  app_name:
    description: 'The name of this app - used as the folder in the CDN bucket and the first part of the URL path'
    required: true

  node_auth_token:
    description: 'Used to install dependencies from our private repos'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Source
      uses: actions/checkout@v1

    - name: Setup NodeJS 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: https://npm.pkg.github.com/
        scope: '@uw-it-sis'

    - name: Install NPM dependencies
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node_auth_token }}
        CI: true

    - name: Build
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        # Minify builds on master.
        [[  "${BRANCH_NAME}" = "master" ]] &&  npm run build || npm run build-dev

    - name: Create Archive
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        (tar --transform s/dist/${{ inputs.app_name }}/ -czf - ./dist > ${{ inputs.ARTIFACT }})

