name: 'Build UI'
description: 'Builds the UI artifact for a SIS cloud app'
inputs:

  artifact_s3_bucket:
    description: "The name of the s3 bucket where the lambda code artifact is stored"
    required: true

  artifact_s3_key:
    description: "The path to the artifact within the bucket"
    required: true

  lambda_function_name:
    description: "The full name of the lambda function to deploy to"
    default: "unset"

runs:
  using: "composite"
  steps:
    - name: Determine lambda name
      shell: bash
      id: lambda_name
      run: |
        # per the terraform definition, the lambda name defaults to the name of the code artifact without the extension
        if [[ ${{ inputs.lambda_function_name != "unset" ]]; then
          artifact=$(basename ${{ inputs.artifact_s3_key }})
          name=${artifact%.zip}
        else
          name=${{ inputs.lambda_function_name }}
        fi
        echo "::set-output name=lambda_function_name::$name"


    - name: Deploy App Api
      shell: bash
      run: |
        aws lambda update-function-code \
          --function-name ${{ steps.lambda_name.outputs.lambda_function_name }} \
          --s3-bucket ${{ inputs.artifact_s3_bucket }} \
          --s3-key    ${{ inputs.artifact_s3_key }} \
          > /dev/null # don't print the whole lambda config
