name: 'Build UI'
description: 'Builds the UI artifact for a SIS cloud app'
inputs:

  artifact_s3_bucket:
    description: "The name of the s3 bucket where the lambda code artifact is stored"
    required: true

  artifact_s3_key:
    description: "The path to the artifact within the bucket"
    required: true

  lambda_function_name:
    description: "The full name of the lambda function to deploy to"
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy App Api
      shell: bash
      run: |
        aws lambda update-function-code \
          --function-name ${{ inputs.lambda_function_name }} \
          --s3-bucket ${{ inputs.artifact_s3_bucket }} \
          --s3-key    ${{ inputs.artifact_s3_key }} \
          > /dev/null # don't print the whole lambda config
