name: 'Testing'
description: 'This is at test action'
inputs:
  word:  # id of input
    description: 'A word to echo'
    required: true
    default: 'Bar'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.word }}