name: 'Validate Node Dependencies'
description: 'Validate siscloud node dependencies'
runs:
  using: 'node24'
  main: 'dist/index.js'
inputs:
  workdir:
    description: 'The directory to work from. Can be relative or absolute'
    default: '.'
