name: 'Stage Artifact'
description: "Copies a JS artifact to the appropriate S3 bucket so that it's available for deployment"
inputs:
  workdir:
    description: 'The directory to work from. Can be relative or absolute'
    default: '.'
  collective:
    description: 'The collective prefix of the S3 bucket'
    required: true
  bucketBase:
    description: 'The base name of the S3 buckets'
    required: true
  artifact:
    description: 'The name of the artifact'
    required: true
  repoOverride:
    description: 'An alternate name for the repo. If not provided the repo name will be extracted from the GITHUB_REPOSITORY variable'
    default: 'unset'
  aws-region:
    description: 'The region where the artifact should be deployed'
    default: 'unset'
outputs:
  artifactBucket:
    description: 'The name of the artifact bucket the object was uploaded to'
  branch:
    description: 'The name of the branch'
  version:
    description: 'The version of the artifact which was read from package.json'
  s3Object:
    description: 'The path of the S3 object within the bucket'
  s3ArtifactUri:
    description: 'The full S3Uri path to the staged artifact'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workdir }}
    - ${{ inputs.collective }}
    - ${{ inputs.bucketBase }}
    - ${{ inputs.artifact }}
    - ${{ inputs.repoOverride }}