name: 'Stage Artifact'
description: 'Copies a JS artifact to the appropriate S3 bucket so that it's available for deployment.'
inputs:
  bucketBase: # id of output
    description: 'The base name of the S3 buckets'
    required: true
  artifact:
    description: 'The name of the artifact'
    required: true
  repoOverride:  # id of input
    description: 'An alternate name for the repo. If not provided the repo name will be extracted from the GITHUB_REPOSITORY variable.'
    default: 'unset'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bucketBase }}
    - ${{ inputs.artifact }}
    - ${{ inputs.repoOverride }}