name: 'Stage Artifact'
description: "Copies a JS artifact to the appropriate S3 bucket so that it's available for deployment."
inputs:
  workdir: # id of output
    description: 'The directory to work from. Can be relative or absolute.'
    default: './'
  bucketBase: # id of output
    description: 'The base name of the S3 buckets'
    required: true
  artifact:
    description: 'The name of the artifact'
    required: true
  repoOverride:  # id of input
    description: 'An alternate name for the repo. If not provided the repo name will be extracted from the GITHUB_REPOSITORY variable.'
    default: 'unset'
outputs:
  artifactBucket:
    description: 'The name of the artifact bucket that was calculated'
  branch:
    description: 'The name of the branch.'
  version:
    description: 'The version of the artifact'
  s3Object:
    description: 'The name of the S3 object.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workdir }}
    - ${{ inputs.bucketBase }}
    - ${{ inputs.artifact }}
    - ${{ inputs.repoOverride }}